import { Router } from "express";
import { z } from "zod";
import { randomUUID } from "node:crypto";
import { requireActiveSubscription, requireAuth, requireCompany, requirePermission } from "../middleware/auth.js";
import { getPrisma } from "../lib/website-builder-prisma.js";
import type { RequestWithAccess } from "../types/access.js";

export const contractClausesRouter = Router();
contractClausesRouter.use(requireAuth, requireCompany, requireActiveSubscription);
const db = () => getPrisma() as any;
const typeSchema = z.enum(["rental", "sale"]);
const clauseSchema = z.object({ id: z.string().uuid().optional(), contract_type: typeSchema, category: z.string().trim().min(2).max(80), title: z.string().trim().min(2).max(240), content: z.string().trim().min(2).max(20000) });
const instanceSchema = z.object({ source_clause_id: z.string().uuid().nullable().optional(), title: z.string().trim().min(2).max(240), content: z.string().trim().min(2).max(20000), position: z.number().int().nonnegative().optional() });
const SYSTEM_CLAUSES = [
  ["rental", "aluguel", "Aluguel e vencimento", "O aluguel e seu vencimento observarão as condições expressamente acordadas pelas partes."],
  ["rental", "vistoria", "Vistoria e conservação", "As partes reconhecem a importância da vistoria e da conservação do imóvel durante a vigência contratual."],
  ["sale", "pagamento", "Preço e pagamento", "O preço e as condições de pagamento serão aqueles definidos neste instrumento e seus anexos."],
  ["sale", "posse", "Posse e entrega", "A posse será transmitida conforme as condições e datas expressamente previstas neste instrumento."],
] as const;
function notFound() { return Object.assign(new Error("Contrato ou cláusula não encontrado."), { statusCode: 404, code: "NOT_FOUND" }); }
function serialize(row: any) { return { id: row.id, company_id: row.companyId, contract_type: row.contractType, category: row.category, title: row.title, content: row.content, active: row.active, system: row.companyId === null, created_at: row.createdAt.toISOString(), updated_at: row.updatedAt.toISOString() }; }
async function findContract(req: RequestWithAccess, id: string) { const row = await db().contract.findFirst({ where: { id, companyId: req.access!.company.id }, select: { id: true, companyId: true, status: true } }); if (!row) throw notFound(); return row; }

contractClausesRouter.get("/", requirePermission("contracts.view"), async (req: RequestWithAccess, res, next) => { try { const type = typeof req.query.contract_type === "string" && ["rental", "sale"].includes(req.query.contract_type) ? req.query.contract_type : undefined; const rows = await db().contractClause.findMany({ where: { OR: [{ companyId: null }, { companyId: req.access!.company.id }], ...(type ? { contractType: type } : {}), active: true }, orderBy: [{ category: "asc" }, { title: "asc" }] }); const systemRows = SYSTEM_CLAUSES.filter(([contractType]) => !type || contractType === type).map(([contractType, category, title, content], index) => ({ id: `00000000-0000-4000-8000-${String(index + 1).padStart(12, "0")}`, companyId: null, contractType, category, title, content, active: true, createdAt: new Date(0), updatedAt: new Date(0) })); res.json({ clauses: [...systemRows, ...rows].map(serialize) }); } catch (e) { next(e); } });
contractClausesRouter.post("/", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const input = clauseSchema.parse(req.body); const row = await db().contractClause.create({ data: { id: input.id ?? randomUUID(), companyId: req.access!.company.id, contractType: input.contract_type, category: input.category, title: input.title, content: input.content, createdBy: req.access!.appUser.id } }); res.status(201).json({ clause: serialize(row) }); } catch (e) { next(e); } });
contractClausesRouter.patch("/:id", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const input = clauseSchema.omit({ id: true }).partial().parse(req.body); const row = await db().contractClause.findFirst({ where: { id: String(req.params.id), companyId: req.access!.company.id } }); if (!row) throw notFound(); const updated = await db().contractClause.update({ where: { id: row.id }, data: { ...(input.contract_type ? { contractType: input.contract_type } : {}), ...(input.category ? { category: input.category } : {}), ...(input.title ? { title: input.title } : {}), ...(input.content ? { content: input.content } : {}) } }); res.json({ clause: serialize(updated) }); } catch (e) { next(e); } });
contractClausesRouter.delete("/:id", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const row = await db().contractClause.findFirst({ where: { id: String(req.params.id), companyId: req.access!.company.id } }); if (!row) throw notFound(); const used = await db().contractClauseInstance.count({ where: { sourceClauseId: row.id } }); if (used) { await db().contractClause.update({ where: { id: row.id }, data: { active: false } }); } else await db().contractClause.delete({ where: { id: row.id } }); res.json({ ok: true }); } catch (e) { next(e); } });

contractClausesRouter.get("/system/seed", requirePermission("contracts.manage"), async (_req, res) => { res.json({ clauses: SYSTEM_CLAUSES.map(([contract_type, category, title, content]) => ({ contract_type, category, title, content, system: true })) }); });
contractClausesRouter.get("/contracts/:contractId", requirePermission("contracts.view"), async (req: RequestWithAccess, res, next) => { try { const contract = await findContract(req, String(req.params.contractId)); const rows = await db().contractClauseInstance.findMany({ where: { contractId: contract.id, companyId: contract.companyId }, orderBy: { position: "asc" } }); res.json({ clauses: rows }); } catch (e) { next(e); } });
contractClausesRouter.post("/contracts/:contractId", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const contract = await findContract(req, String(req.params.contractId)); if (["signed", "active", "cancelled", "terminated", "archived"].includes(contract.status)) throw Object.assign(new Error("Contrato imutável."), { statusCode: 409 }); const input = instanceSchema.parse(req.body); if (input.source_clause_id) { const source = await db().contractClause.findFirst({ where: { id: input.source_clause_id, active: true, OR: [{ companyId: null }, { companyId: contract.companyId }], contractType: (await db().contract.findUnique({ where: { id: contract.id }, select: { contractType: true } })).contractType } }); if (!source) throw notFound(); } const max = await db().contractClauseInstance.aggregate({ where: { contractId: contract.id }, _max: { position: true } }); const row = await db().contractClauseInstance.create({ data: { id: randomUUID(), companyId: contract.companyId, contractId: contract.id, sourceClauseId: input.source_clause_id ?? null, title: input.title, content: input.content, position: input.position ?? ((max._max.position ?? -1) + 1), metadataJson: { source: input.source_clause_id ? "library" : "custom" } } }); res.status(201).json({ clause: row }); } catch (e) { next(e); } });
contractClausesRouter.patch("/contracts/:contractId/:clauseId", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const contract = await findContract(req, String(req.params.contractId)); if (["signed", "active", "cancelled", "terminated", "archived"].includes(contract.status)) throw Object.assign(new Error("Contrato imutável."), { statusCode: 409 }); const input = instanceSchema.partial().parse(req.body); const row = await db().contractClauseInstance.findFirst({ where: { id: String(req.params.clauseId), contractId: contract.id, companyId: contract.companyId } }); if (!row) throw notFound(); const updated = await db().contractClauseInstance.update({ where: { id: row.id }, data: { ...(input.title ? { title: input.title } : {}), ...(input.content ? { content: input.content } : {}), ...(input.position !== undefined ? { position: input.position } : {}) } }); res.json({ clause: updated }); } catch (e) { next(e); } });
contractClausesRouter.delete("/contracts/:contractId/:clauseId", requirePermission("contracts.manage"), async (req: RequestWithAccess, res, next) => { try { const contract = await findContract(req, String(req.params.contractId)); const row = await db().contractClauseInstance.findFirst({ where: { id: String(req.params.clauseId), contractId: contract.id, companyId: contract.companyId } }); if (!row) throw notFound(); await db().contractClauseInstance.delete({ where: { id: row.id } }); res.json({ ok: true }); } catch (e) { next(e); } });
