CREATE TABLE `owner_property_update_requests` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `property_id` CHAR(36) NOT NULL,
  `type` VARCHAR(40) NOT NULL,
  `reason` TEXT NOT NULL,
  `status` VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  `previous_publication_state` JSON NULL,
  `requested_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `resolved_at` DATETIME(3) NULL,
  `resolved_by` CHAR(36) NULL,
  `resolution_note` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `owner_property_update_requests_company_status_requested_at_idx` (`company_id`, `status`, `requested_at`),
  INDEX `owner_property_update_requests_company_owner_requested_at_idx` (`company_id`, `owner_id`, `requested_at`),
  INDEX `owner_property_update_requests_company_property_status_idx` (`company_id`, `property_id`, `status`),
  INDEX `owner_property_update_requests_resolved_by_idx` (`resolved_by`),
  CONSTRAINT `owner_property_update_requests_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_property_update_requests_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `property_owners` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_property_update_requests_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_property_update_requests_resolved_by_fkey` FOREIGN KEY (`resolved_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
