-- P1 Owner Profile/Enrichment. Additive only: no existing table or row is modified.
CREATE TABLE `owner_profiles` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `identity_json` JSON NOT NULL,
  `contact_json` JSON NOT NULL,
  `address_json` JSON NOT NULL,
  `professional_json` JSON NOT NULL,
  `financial_json` JSON NOT NULL,
  `credit_json` JSON NOT NULL,
  `legal_json` JSON NOT NULL,
  `fiscal_json` JSON NOT NULL,
  `provenance_json` JSON NOT NULL,
  `confidence_json` JSON NOT NULL,
  `treatment_consent_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `owner_profiles_owner_id_key` (`owner_id`),
  UNIQUE KEY `owner_profiles_company_id_owner_id_key` (`company_id`, `owner_id`),
  KEY `owner_profiles_company_id_updated_at_idx` (`company_id`, `updated_at`),
  CONSTRAINT `owner_profiles_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `owner_profiles_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `property_owners` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `owner_checks` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `check_type` VARCHAR(40) NOT NULL,
  `provider` VARCHAR(100) NOT NULL,
  `status` VARCHAR(30) NOT NULL,
  `input_fingerprint` VARCHAR(128) NOT NULL,
  `idempotency_key` VARCHAR(160) NOT NULL,
  `source` VARCHAR(80) NULL,
  `summary_json` JSON NULL,
  `warnings_json` JSON NULL,
  `requested_by` CHAR(36) NULL,
  `checked_at` DATETIME(3) NULL,
  `expires_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `owner_checks_company_owner_type_provider_key` (`company_id`, `owner_id`, `check_type`, `provider`, `idempotency_key`),
  KEY `owner_checks_company_owner_type_checked_idx` (`company_id`, `owner_id`, `check_type`, `checked_at`),
  KEY `owner_checks_company_status_expires_idx` (`company_id`, `status`, `expires_at`),
  CONSTRAINT `owner_checks_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `owner_checks_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `property_owners` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_checks_requested_by_fkey` FOREIGN KEY (`requested_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `owner_document_records` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `stored_file_id` CHAR(36) NOT NULL,
  `document_type` VARCHAR(60) NOT NULL,
  `status` VARCHAR(30) NOT NULL DEFAULT 'PENDING',
  `verified` BOOLEAN NOT NULL DEFAULT false,
  `verified_by` CHAR(36) NULL,
  `verified_at` DATETIME(3) NULL,
  `expires_at` DATETIME(3) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `owner_document_records_stored_file_id_key` (`stored_file_id`),
  KEY `owner_document_records_company_owner_type_idx` (`company_id`, `owner_id`, `document_type`),
  KEY `owner_document_records_company_status_expires_idx` (`company_id`, `status`, `expires_at`),
  CONSTRAINT `owner_document_records_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `owner_document_records_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `property_owners` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_document_records_stored_file_id_fkey` FOREIGN KEY (`stored_file_id`) REFERENCES `stored_files` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `owner_document_records_verified_by_fkey` FOREIGN KEY (`verified_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
