CREATE TABLE `website_audit_logs` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `website_id` CHAR(36) NULL,
  `page_id` CHAR(36) NULL,
  `section_id` CHAR(36) NULL,
  `component_id` CHAR(36) NULL,
  `asset_id` CHAR(36) NULL,
  `actor_user_id` CHAR(36) NULL,
  `action` ENUM(
    'website_created',
    'website_updated',
    'website_deleted',
    'website_cloned',
    'page_created',
    'page_updated',
    'page_deleted',
    'section_created',
    'section_updated',
    'section_deleted',
    'component_created',
    'component_updated',
    'component_deleted',
    'asset_upload_requested',
    'asset_uploaded',
    'asset_deleted',
    'domain_created',
    'domain_updated',
    'domain_deleted',
    'seo_updated'
  ) NOT NULL,
  `entity_type` VARCHAR(80) NOT NULL,
  `entity_id` CHAR(36) NULL,
  `summary` VARCHAR(240) NULL,
  `metadata_json` JSON NOT NULL,
  `ip_address` VARCHAR(80) NULL,
  `user_agent` VARCHAR(300) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `website_audit_logs_company_id_website_id_created_at_idx` (`company_id`, `website_id`, `created_at`),
  KEY `website_audit_logs_company_id_action_created_at_idx` (`company_id`, `action`, `created_at`),
  KEY `website_audit_logs_website_id_idx` (`website_id`),
  KEY `website_audit_logs_page_id_idx` (`page_id`),
  KEY `website_audit_logs_section_id_idx` (`section_id`),
  KEY `website_audit_logs_component_id_idx` (`component_id`),
  KEY `website_audit_logs_asset_id_idx` (`asset_id`),
  CONSTRAINT `website_audit_logs_website_id_fkey` FOREIGN KEY (`website_id`) REFERENCES `websites`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `website_audit_logs_page_id_fkey` FOREIGN KEY (`page_id`) REFERENCES `website_pages`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `website_audit_logs_section_id_fkey` FOREIGN KEY (`section_id`) REFERENCES `website_sections`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `website_audit_logs_component_id_fkey` FOREIGN KEY (`component_id`) REFERENCES `website_components`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `website_audit_logs_asset_id_fkey` FOREIGN KEY (`asset_id`) REFERENCES `website_assets`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
