CREATE TABLE IF NOT EXISTS `companies` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `document` VARCHAR(40) NULL,
  `phone` VARCHAR(40) NULL,
  `email` VARCHAR(160) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `companies_status_idx` (`status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `users` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `role_id` CHAR(36) NULL,
  `name` VARCHAR(160) NOT NULL,
  `email` VARCHAR(180) NOT NULL,
  `phone` VARCHAR(40) NULL,
  `password_hash` VARCHAR(180) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `role` VARCHAR(60) NOT NULL DEFAULT 'owner',
  `permissions_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_company_id_email_key` (`company_id`, `email`),
  KEY `users_email_idx` (`email`),
  CONSTRAINT `users_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `subscriptions` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `plan_slug` VARCHAR(80) NULL,
  `expires_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `subscriptions_company_id_status_idx` (`company_id`, `status`),
  CONSTRAINT `subscriptions_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `property_owners` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `created_by` CHAR(36) NULL,
  `owner_type` VARCHAR(40) NOT NULL DEFAULT 'individual',
  `client_type` VARCHAR(40) NOT NULL DEFAULT 'proprietario',
  `name` VARCHAR(180) NOT NULL,
  `document` VARCHAR(40) NULL,
  `email` VARCHAR(180) NULL,
  `phone` VARCHAR(40) NULL,
  `whatsapp` VARCHAR(40) NULL,
  `residential_phone` VARCHAR(40) NULL,
  `commercial_phone` VARCHAR(40) NULL,
  `address_json` JSON NOT NULL,
  `notes` TEXT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'active',
  `portal_token` VARCHAR(120) NULL,
  `portal_enabled` BOOLEAN NOT NULL DEFAULT false,
  `portal_last_access_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `property_owners_company_id_status_idx` (`company_id`, `status`),
  CONSTRAINT `property_owners_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `properties` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NULL,
  `created_by` CHAR(36) NULL,
  `code` VARCHAR(40) NULL,
  `title` VARCHAR(220) NOT NULL,
  `description` TEXT NULL,
  `property_type` VARCHAR(40) NOT NULL DEFAULT 'apartment',
  `operation` VARCHAR(40) NOT NULL DEFAULT 'sale',
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `street` VARCHAR(180) NULL,
  `number` VARCHAR(40) NULL,
  `complement` VARCHAR(120) NULL,
  `neighborhood` VARCHAR(120) NULL,
  `city` VARCHAR(120) NULL,
  `state` VARCHAR(40) NULL,
  `zip_code` VARCHAR(20) NULL,
  `country` VARCHAR(80) NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `condominium_name` VARCHAR(160) NULL,
  `nearby_highways` JSON NOT NULL,
  `responsible_user_id` CHAR(36) NULL,
  `capture_json` JSON NOT NULL,
  `primary_details_json` JSON NOT NULL,
  `measurements_json` JSON NOT NULL,
  `sale_price_cents` INTEGER NULL,
  `rent_price_cents` INTEGER NULL,
  `condominium_fee_cents` INTEGER NULL,
  `iptu_cents` INTEGER NULL,
  `commercial_terms_json` JSON NOT NULL,
  `features_json` JSON NOT NULL,
  `amenity_groups_json` JSON NOT NULL,
  `videos_json` JSON NOT NULL,
  `publication_settings_json` JSON NOT NULL,
  `description_template_key` VARCHAR(100) NULL,
  `private_area` DOUBLE NULL,
  `total_area` DOUBLE NULL,
  `bedrooms` INTEGER NULL,
  `bathrooms` INTEGER NULL,
  `suites` INTEGER NULL,
  `parking_spaces` INTEGER NULL,
  `published_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `properties_company_id_code_key` (`company_id`, `code`),
  KEY `properties_company_id_status_published_at_idx` (`company_id`, `status`, `published_at`),
  KEY `properties_company_id_operation_idx` (`company_id`, `operation`),
  KEY `properties_company_id_city_neighborhood_idx` (`company_id`, `city`, `neighborhood`),
  KEY `properties_owner_id_idx` (`owner_id`),
  CONSTRAINT `properties_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `properties_owner_id_fkey` FOREIGN KEY (`owner_id`) REFERENCES `property_owners`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `property_owner_links` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `property_id` CHAR(36) NOT NULL,
  `owner_id` CHAR(36) NOT NULL,
  `is_main_owner` BOOLEAN NOT NULL DEFAULT false,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `property_owner_links_company_id_property_id_owner_id_key` (`company_id`, `property_id`, `owner_id`),
  KEY `property_owner_links_company_id_property_id_idx` (`company_id`, `property_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `property_media` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `property_id` CHAR(36) NOT NULL,
  `media_type` VARCHAR(40) NOT NULL DEFAULT 'photo',
  `url` VARCHAR(1200) NOT NULL,
  `caption` VARCHAR(240) NULL,
  `position` INTEGER NOT NULL DEFAULT 0,
  `storage_bucket` VARCHAR(160) NULL,
  `storage_path` VARCHAR(700) NULL,
  `mime_type` VARCHAR(120) NULL,
  `file_size` INTEGER NULL,
  `is_cover` BOOLEAN NOT NULL DEFAULT false,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `property_media_company_id_property_id_position_idx` (`company_id`, `property_id`, `position`),
  CONSTRAINT `property_media_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `company_sites` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `created_by` CHAR(36) NULL,
  `slug` VARCHAR(100) NOT NULL,
  `custom_domain` VARCHAR(180) NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'draft',
  `brand_name` VARCHAR(180) NOT NULL,
  `headline` VARCHAR(280) NULL,
  `description` TEXT NULL,
  `phone` VARCHAR(40) NULL,
  `whatsapp` VARCHAR(40) NULL,
  `email` VARCHAR(180) NULL,
  `logo_url` VARCHAR(900) NULL,
  `primary_color` VARCHAR(40) NOT NULL DEFAULT '#c8a24b',
  `settings_json` JSON NOT NULL,
  `seo_json` JSON NOT NULL,
  `published_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `company_sites_company_id_slug_key` (`company_id`, `slug`),
  UNIQUE KEY `company_sites_custom_domain_key` (`custom_domain`),
  KEY `company_sites_slug_status_idx` (`slug`, `status`),
  KEY `company_sites_company_id_status_idx` (`company_id`, `status`),
  CONSTRAINT `company_sites_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `leads` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `stage_id` CHAR(36) NULL,
  `created_by` CHAR(36) NULL,
  `name` VARCHAR(180) NOT NULL,
  `email` VARCHAR(180) NULL,
  `phone` VARCHAR(40) NULL,
  `source` VARCHAR(80) NOT NULL DEFAULT 'site',
  `interest_type` VARCHAR(60) NOT NULL DEFAULT 'not_defined',
  `property_reference` VARCHAR(220) NULL,
  `notes` TEXT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `leads_company_id_source_created_at_idx` (`company_id`, `source`, `created_at`),
  CONSTRAINT `leads_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `site_leads` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `site_id` CHAR(36) NULL,
  `property_id` CHAR(36) NULL,
  `lead_id` CHAR(36) NULL,
  `name` VARCHAR(180) NOT NULL,
  `email` VARCHAR(180) NULL,
  `phone` VARCHAR(40) NULL,
  `message` TEXT NULL,
  `source_url` VARCHAR(900) NULL,
  `ip_address` VARCHAR(80) NULL,
  `user_agent` VARCHAR(300) NULL,
  `metadata` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `site_leads_company_id_site_id_created_at_idx` (`company_id`, `site_id`, `created_at`),
  KEY `site_leads_company_id_property_id_idx` (`company_id`, `property_id`),
  CONSTRAINT `site_leads_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `site_leads_site_id_fkey` FOREIGN KEY (`site_id`) REFERENCES `company_sites`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `site_leads_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `site_leads_lead_id_fkey` FOREIGN KEY (`lead_id`) REFERENCES `leads`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `appointments` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `property_id` CHAR(36) NULL,
  `created_by` CHAR(36) NULL,
  `appointment_type` VARCHAR(60) NOT NULL DEFAULT 'visit',
  `title` VARCHAR(180) NOT NULL,
  `description` TEXT NULL,
  `location_text` VARCHAR(240) NULL,
  `starts_at` DATETIME(3) NOT NULL,
  `ends_at` DATETIME(3) NOT NULL,
  `reminder_at` DATETIME(3) NULL,
  `metadata` JSON NOT NULL,
  `status` VARCHAR(40) NOT NULL DEFAULT 'scheduled',
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  KEY `appointments_company_id_property_id_idx` (`company_id`, `property_id`),
  KEY `appointments_company_id_starts_at_idx` (`company_id`, `starts_at`),
  CONSTRAINT `appointments_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `appointments_property_id_fkey` FOREIGN KEY (`property_id`) REFERENCES `properties`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
