import {
  BarChart3,
  Bell,
  BrainCircuit,
  Building2,
  Activity,
  FlaskConical,
  Gauge,
  CalendarDays,
  ClipboardList,
  FileSignature,
  Home,
  Upload,
  Globe2,
  PlugZap,
  KeyRound,
  Settings,
  Users,
  WalletCards,
} from "lucide-react";

export const appModules = [
  {
    key: "dashboard",
    label: "Dashboard",
    path: "/app",
    icon: BarChart3,
    title: "Dashboard",
    description: "Indicadores reais da imobiliária, sem dados demonstrativos.",
    emptyTitle: "Nenhum dado operacional ainda",
    emptyDescription:
      "Os indicadores serão preenchidos conforme imóveis, leads, contratos, visitas e lançamentos reais forem cadastrados.",
    actionLabel: "Cadastrar primeiro imóvel",
  },
  {
    key: "crm",
    label: "CRM",
    path: "/app/crm",
    icon: Users,
    title: "CRM imobiliário",
    description: "Leads, funil, tarefas, follow-ups e histórico de atendimento.",
    emptyTitle: "Nenhum lead encontrado",
    emptyDescription:
      "Leads aparecerão aqui quando forem cadastrados manualmente ou capturados por integrações reais.",
    actionLabel: "Cadastrar lead",
  },
  {
    key: "properties",
    label: "Imóveis",
    path: "/app/imoveis",
    icon: Home,
    title: "Gestão de imóveis",
    description: "Cadastro, status, valores, fotos, documentos e proprietário vinculado.",
    emptyTitle: "Nenhum imóvel cadastrado",
    emptyDescription: "Cadastre o primeiro imóvel ou importe uma base real quando a importação estiver ativa.",
    actionLabel: "Cadastrar imóvel",
  },
  {
    key: "owners",
    label: "Proprietários",
    path: "/app/proprietarios",
    icon: KeyRound,
    title: "Proprietários",
    description: "Pessoas e empresas donas dos imóveis, com documentos e vínculos.",
    emptyTitle: "Nenhum proprietário cadastrado",
    emptyDescription:
      "Proprietários serão vinculados aos imóveis reais cadastrados pela equipe.",
    actionLabel: "Cadastrar proprietário",
  },
  {
    key: "agenda",
    label: "Agenda",
    path: "/app/agenda",
    icon: CalendarDays,
    title: "Agenda e visitas",
    description: "Visitas, reuniões, vistorias, retornos e lembretes internos.",
    emptyTitle: "Nenhum compromisso agendado",
    emptyDescription:
      "Compromissos serão criados a partir de leads, imóveis e rotinas reais da imobiliária.",
    actionLabel: "Agendar visita",
  },
  {
    key: "inspections",
    label: "Vistorias",
    path: "/app/vistorias",
    icon: ClipboardList,
    title: "Vistoria inteligente",
    description: "Vistoria por cômodo, fotos, observações, assinaturas e PDF.",
    emptyTitle: "Nenhuma vistoria criada",
    emptyDescription:
      "As vistorias aparecerão aqui depois que um imóvel real for selecionado para entrada, saída ou manutenção.",
    actionLabel: "Criar vistoria",
  },
  {
    key: "contracts",
    label: "Contratos",
    path: "/app/contratos",
    icon: FileSignature,
    title: "Contratos e documentos",
    description: "Modelos, geração, anexos, status e assinatura digital.",
    emptyTitle: "Nenhum contrato criado",
    emptyDescription:
      "Contratos serão criados a partir de imóveis, vendas, locações ou modelos reais.",
    actionLabel: "Criar contrato",
  },
  {
    key: "finance",
    label: "Financeiro",
    path: "/app/financeiro",
    icon: WalletCards,
    title: "Financeiro",
    description: "Recebíveis, pagamentos, comissões, repasses e fluxo de caixa.",
    emptyTitle: "Nenhum lançamento financeiro",
    emptyDescription:
      "Valores financeiros só serão exibidos após registros reais de venda, locação, cobrança ou despesa.",
    actionLabel: "Criar lançamento",
  },
  {
    key: "notifications",
    label: "Notificações",
    path: "/app/notificacoes",
    icon: Bell,
    title: "Notificações",
    description: "Histórico de mensagens, links enviados e régua de cobrança.",
    emptyTitle: "Nenhuma notificação registrada",
    emptyDescription:
      "Os registros aparecerão quando links de portal, cobranças, lembretes e avisos forem preparados ou enviados.",
    actionLabel: "Revisar templates",
  },
  {
    key: "ai",
    label: "IA",
    path: "/app/inteligencia",
    icon: BrainCircuit,
    title: "IA imobiliária",
    description: "Solicitações, templates, créditos e histórico de IA com dados reais.",
    emptyTitle: "Nenhuma solicitação de IA registrada",
    emptyDescription:
      "A IA aparecerá aqui quando houver dados reais de imóveis, leads, vistorias ou contratos para gerar textos e análises.",
    actionLabel: "Registrar solicitação",
  },
  {
    key: "operations",
    label: "Operações",
    path: "/app/operacoes",
    icon: Activity,
    title: "Centro operacional",
    description: "Saúde de automações, webhooks, filas, entregas e falhas técnicas.",
    emptyTitle: "Nenhum evento operacional ainda",
    emptyDescription:
      "Este painel será preenchido conforme notificações, webhooks e automações forem executados com dados reais.",
    actionLabel: "Atualizar operação",
  },
  {
    key: "tests",
    label: "Testes",
    path: "/app/testes",
    icon: FlaskConical,
    title: "Laboratório de testes",
    description: "Cenários automáticos de QA em modo preview para imóveis, agenda e vistorias.",
    emptyTitle: "Nenhum cenário de teste executado",
    emptyDescription:
      "Gere cenários apenas no modo preview para validar o sistema sem inserir dados fictícios em produção.",
    actionLabel: "Gerar testes",
  },
  {
    key: "site",
    label: "Site",
    path: "/app/site",
    icon: Globe2,
    title: "Site da imobiliária",
    description: "Site público conectado aos imóveis reais e ao CRM.",
    emptyTitle: "Site ainda não configurado",
    emptyDescription:
      "Configure a vitrine pública da imobiliária e publique apenas imóveis reais cadastrados.",
    actionLabel: "Configurar site",
  },
  {
    key: "imports",
    label: "Importação",
    path: "/app/importacoes",
    icon: Upload,
    title: "Importação de dados",
    description: "Migração CSV de imóveis e proprietários com prévia, validação e relatório.",
    emptyTitle: "Nenhuma importação realizada",
    emptyDescription:
      "Importe uma base real em CSV para iniciar imóveis e proprietários sem recadastro manual.",
    actionLabel: "Importar CSV",
  },
  {
    key: "integrations",
    label: "Integrações",
    path: "/app/integracoes",
    icon: PlugZap,
    title: "Integrações externas",
    description: "WhatsApp, portais, pagamentos, Google e enriquecimento de dados.",
    emptyTitle: "Nenhuma integração conectada",
    emptyDescription:
      "Configure credenciais seguras para conectar canais externos sem expor segredos no frontend.",
    actionLabel: "Configurar integração",
  },
  {
    key: "settings",
    label: "Configurações",
    path: "/app/configuracoes",
    icon: Settings,
    title: "Configurações",
    description: "Empresa, usuários, permissões, plano e integrações.",
    emptyTitle: "Configurações iniciais pendentes",
    emptyDescription:
      "Complete os dados da empresa e convide usuários quando a assinatura estiver ativa.",
    actionLabel: "Revisar empresa",
  },
  {
    key: "costs",
    label: "Custos",
    path: "/app/custos",
    icon: Gauge,
    title: "Custos por imobiliária",
    description: "Consumo operacional, margem estimada e saúde econômica do tenant.",
    emptyTitle: "Nenhum consumo operacional registrado",
    emptyDescription:
      "Os custos serão exibidos quando o sistema registrar uso real de IA, PDFs, armazenamento, mensagens, cobranças ou API.",
    actionLabel: "Ver catálogo de custos",
  },
];

export type AppModule = (typeof appModules)[number];

export function getModuleByKey(key: string) {
  return appModules.find((module) => module.key === key) ?? appModules[0];
}
