import { ClipboardList, Loader2, Plus } from "lucide-react";
import { useEffect, useState } from "react";
import { createFileRoute, Link } from "@tanstack/react-router";
import { EmptyState } from "@/components/app/empty-state";
import { ModulePage } from "@/components/app/module-page";
import { getModuleByKey } from "@/product/app-modules";
import { canManage, getSafeApiErrorMessage } from "@/product/app-access";
import { createMysqlInspection, listMysqlInspections, type MysqlInspection, type MysqlInspectionPage, type MysqlInspectionStatus } from "@/product/inspections";
import { listProperties, listPropertyEligibleUsers, type PropertySummary } from "@/product/real-estate";
import { useSessionGuard } from "@/product/use-session-guard";

export const Route = createFileRoute("/app/vistorias")({ component: InspectionsPage });
const statusLabels: Record<MysqlInspectionStatus, string> = { draft: "Rascunho", in_progress: "Em andamento", completed: "Concluída", archived: "Arquivada" };
const typeLabels = { entry: "Entrada", exit: "Saída" };

function InspectionsPage() {
  const { session, isLoading } = useSessionGuard();
  const [rows, setRows] = useState<MysqlInspection[]>([]); const [properties, setProperties] = useState<PropertySummary[]>([]); const [users, setUsers] = useState<Array<{ id: string; name: string }>>([]); const [page, setPage] = useState(1); const [status, setStatus] = useState<MysqlInspectionStatus | undefined>(); const [pagination, setPagination] = useState<MysqlInspectionPage["pagination"] | null>(null); const [loading, setLoading] = useState(true); const [showForm, setShowForm] = useState(false); const [error, setError] = useState<string | null>(null);
  const module = getModuleByKey("inspections"); const canCreate = canManage(session?.access.appUser, "inspections.manage");
  async function refresh() { setLoading(true); setError(null); try { const [ip, pp, up] = await Promise.all([listMysqlInspections(page, 25, status), listProperties({ page: 1, pageSize: 100 }), listPropertyEligibleUsers()]); setRows(ip.inspections); setPagination(ip.pagination); setProperties(pp.items); setUsers(up.users); } catch (e) { setError(getSafeApiErrorMessage(e, "Não foi possível carregar as vistorias.")); } finally { setLoading(false); } }
  useEffect(() => { if (!isLoading && session) void refresh(); }, [isLoading, session, page, status]);
  if (isLoading) return <main className="flex min-h-screen items-center justify-center text-sm text-muted-foreground">Validando acesso...</main>;
  return <ModulePage session={session} module={module}><div className="mb-4 flex flex-col gap-3 rounded-lg border border-border bg-card p-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-base font-semibold">Vistorias</h2><p className="text-sm text-muted-foreground">Acompanhe laudos vinculados aos imóveis da sua empresa.</p></div>{canCreate ? <button type="button" onClick={() => setShowForm((v) => !v)} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />Nova vistoria</button> : null}</div>
    <div className="mb-4 flex flex-wrap items-center gap-2"><label className="text-sm font-medium" htmlFor="inspection-status">Status</label><select id="inspection-status" value={status ?? "all"} onChange={(e) => { setPage(1); setStatus(e.target.value === "all" ? undefined : e.target.value as MysqlInspectionStatus); }} className="h-9 rounded-md border border-input bg-background px-3 text-sm"><option value="all">Todos</option>{Object.entries(statusLabels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><span className="text-sm text-muted-foreground">{pagination?.total ?? 0} vistoria(s)</span></div>
    {showForm && canCreate ? <NewInspectionForm properties={properties} onCancel={() => setShowForm(false)} onCreated={() => { setShowForm(false); setPage(1); void refresh(); }} /> : null}{error ? <div role="alert" className="mb-4 rounded-md border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{error}</div> : null}
    {loading ? <div className="flex min-h-[240px] items-center justify-center rounded-lg border border-border bg-card text-sm text-muted-foreground"><Loader2 className="mr-2 h-4 w-4 animate-spin" />Carregando vistorias...</div> : rows.length === 0 ? <EmptyState icon={ClipboardList} title="Nenhuma vistoria encontrada" description="Crie uma vistoria vinculada a um imóvel para iniciar o acompanhamento." actionLabel={canCreate ? "Criar vistoria" : undefined} onAction={canCreate ? () => setShowForm(true) : undefined} /> : <><section className="grid gap-3 lg:grid-cols-2">{rows.map((inspection) => <Link key={inspection.id} to="/app/vistorias/$inspectionId" params={{ inspectionId: inspection.id }} className="rounded-lg border border-border bg-card p-4 transition hover:border-primary focus:outline-none focus:ring-2 focus:ring-ring"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{inspection.property?.code || "Imóvel"}</p><p className="text-sm text-muted-foreground">{inspection.property?.title || "Imóvel vinculado"}</p></div><span className="rounded-full bg-muted px-2 py-1 text-xs font-medium">{statusLabels[inspection.status]}</span></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><div><dt className="text-xs text-muted-foreground">Tipo</dt><dd>{typeLabels[inspection.type]}</dd></div><div><dt className="text-xs text-muted-foreground">Responsável</dt><dd>{inspection.assigned_user?.name || "Não definido"}</dd></div><div><dt className="text-xs text-muted-foreground">Atualizada</dt><dd>{new Date(inspection.updated_at).toLocaleDateString("pt-BR")}</dd></div><div><dt className="text-xs text-muted-foreground">Versão</dt><dd>{inspection.version}</dd></div></dl></Link>)}</section><div className="mt-4 flex items-center justify-between gap-3"><button type="button" disabled={!pagination?.has_previous} onClick={() => setPage((v) => v - 1)} className="h-10 rounded-md border border-border px-3 text-sm disabled:opacity-40">Anterior</button><span className="text-sm text-muted-foreground">Página {pagination?.page ?? page} de {pagination?.total_pages || 1}</span><button type="button" disabled={!pagination?.has_next} onClick={() => setPage((v) => v + 1)} className="h-10 rounded-md border border-border px-3 text-sm disabled:opacity-40">Próxima</button></div></>}</ModulePage>;
}

function NewInspectionForm({ properties, users = [], onCancel, onCreated }: { properties: PropertySummary[]; users?: Array<{ id: string; name: string }>; onCancel: () => void; onCreated: () => void }) {
  const [propertyId, setPropertyId] = useState(""); const [type, setType] = useState<"entry" | "exit">("entry"); const [assignedUserId, setAssignedUserId] = useState(""); const [notes, setNotes] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null); const [loadedUsers, setLoadedUsers] = useState(users);
  useEffect(() => { if (users.length === 0) void listPropertyEligibleUsers().then((result) => setLoadedUsers(result.users)).catch(() => undefined); }, [users.length]);
  const availableUsers = loadedUsers;
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!propertyId) { setError("Selecione um imóvel."); return; } setSaving(true); setError(null); try { await createMysqlInspection({ id: crypto.randomUUID(), property_id: propertyId, type, ...(assignedUserId ? { assigned_user_id: assignedUserId } : {}), notes: notes.trim() || null }); onCreated(); } catch (e) { setError(getSafeApiErrorMessage(e, "Não foi possível criar a vistoria.")); } finally { setSaving(false); } }
  return <form onSubmit={submit} className="mb-4 space-y-4 rounded-lg border border-border bg-card p-4"><div><h2 className="font-semibold">Nova vistoria</h2><p className="text-sm text-muted-foreground">Escolha um imóvel e o tipo do laudo.</p></div>{error ? <div role="alert" className="rounded-md bg-destructive/10 p-3 text-sm text-destructive">{error}</div> : null}<label className="block text-sm font-medium">Imóvel<select required value={propertyId} onChange={(e) => setPropertyId(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3"><option value="">Selecione...</option>{properties.map((p) => <option key={p.id} value={p.id}>{p.code || "Sem código"} · {p.title}</option>)}</select></label><label className="block text-sm font-medium">Responsável<select value={assignedUserId} onChange={(e) => setAssignedUserId(e.target.value)} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3"><option value="">Responsável padrão</option>{availableUsers.map((user) => <option key={user.id} value={user.id}>{user.name}</option>)}</select></label><label className="block text-sm font-medium">Tipo<select value={type} onChange={(e) => setType(e.target.value as "entry" | "exit")} className="mt-1 h-10 w-full rounded-md border border-input bg-background px-3"><option value="entry">Entrada</option><option value="exit">Saída</option></select></label><label className="block text-sm font-medium">Observações<textarea value={notes} onChange={(e) => setNotes(e.target.value)} rows={3} className="mt-1 w-full rounded-md border border-input bg-background p-3" /></label><div className="flex flex-col-reverse gap-2 sm:flex-row sm:justify-end"><button type="button" onClick={onCancel} className="h-10 rounded-md border border-border px-4 text-sm">Cancelar</button><button disabled={saving} className="inline-flex h-10 items-center justify-center gap-2 rounded-md bg-primary px-4 text-sm font-semibold text-primary-foreground disabled:opacity-50">{saving ? <Loader2 className="h-4 w-4 animate-spin" /> : null}Criar vistoria</button></div></form>;
}
