import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "dotenv";

const envFiles = [
  resolve(process.cwd(), ".env.local"),
  resolve(process.cwd(), "backend/.env.local"),
  resolve(process.cwd(), "../.env.local"),
  resolve(process.cwd(), ".env"),
  resolve(process.cwd(), "backend/.env"),
  resolve(process.cwd(), "../.env"),
];

for (const envFile of envFiles) {
  if (existsSync(envFile)) config({ path: envFile });
}

const required = [] as const;

export type Env = {
  NODE_ENV: string;
  PORT: number;
  APP_URL: string;
  FRONTEND_URL?: string;
  CORS_ORIGIN?: string;
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  DATABASE_URL?: string;
  IMOBIFLOW_LOCAL_DEV_AUTH?: string;
  IMOBIFLOW_LOCAL_DEV_TOKEN?: string;
  IMOBIFLOW_LOCAL_DEV_COMPANY_ID?: string;
  IMOBIFLOW_LOCAL_DEV_USER_ID?: string;
  IMOBIFLOW_LOCAL_DEV_ROLE?: string;
  IMOBIFLOW_AUTH_PROVIDER?: string;
  IMOBIFLOW_MYSQL_AUTH?: string;
  IMOBIFLOW_BOOTSTRAP_EMAIL?: string;
  IMOBIFLOW_BOOTSTRAP_PASSWORD?: string;
  IMOBIFLOW_BOOTSTRAP_COMPANY_NAME?: string;
  JWT_SECRET?: string;
  AUTH_EXPOSE_TEST_TOKENS?: string;
  BILLING_PROVIDER?: string;
  BILLING_PAST_DUE_GRACE_DAYS?: string;
  ALLOW_SYNTHETIC_BILLING_PROVISIONING?: string;
  SYNTHETIC_BILLING_ADMIN_SECRET?: string;
  STORAGE_PROVIDER?: string;
  CLOUDINARY_CLOUD_NAME?: string;
  CLOUDINARY_API_KEY?: string;
  CLOUDINARY_API_SECRET?: string;
  CLOUDINARY_UPLOAD_FOLDER?: string;
  CLOUDINARY_UPLOAD_PRESET?: string;
  IMPORT_MEDIA_CONCURRENCY?: string;
  IMPORT_METRICS_ENABLED?: string;
  R2_ACCOUNT_ID?: string;
  R2_ACCESS_KEY_ID?: string;
  R2_SECRET_ACCESS_KEY?: string;
  R2_BUCKET?: string;
  R2_PUBLIC_BASE_URL?: string;
  KIWIFY_WEBHOOK_SECRET?: string;
  CAKTO_WEBHOOK_SECRET?: string;
  PAYMENT_GATEWAY_WEBHOOK_SECRET?: string;
  IUGU_API_KEY?: string;
  IUGU_WEBHOOK_SECRET?: string;
  PJBANK_API_KEY?: string;
  PJBANK_WEBHOOK_SECRET?: string;
  ASAAS_API_KEY?: string;
  ASAAS_WEBHOOK_SECRET?: string;
  PORTAL_INTEGRATIONS_WEBHOOK_SECRET?: string;
  STRIPE_SECRET_KEY?: string;
  STRIPE_WEBHOOK_SECRET?: string;
  GOOGLE_CLIENT_ID?: string;
  GOOGLE_CLIENT_SECRET?: string;
  GOOGLE_MAPS_API_KEY?: string;
  ZAP_IMOVEIS_CLIENT_ID?: string;
  ZAP_IMOVEIS_CLIENT_SECRET?: string;
  OLX_CLIENT_ID?: string;
  OLX_CLIENT_SECRET?: string;
  VIVA_REAL_CLIENT_ID?: string;
  VIVA_REAL_CLIENT_SECRET?: string;
  RECEITA_FEDERAL_API_KEY?: string;
  RECEITA_FEDERAL_BASE_URL?: string;
  WHATSAPP_PROVIDER_URL?: string;
  WHATSAPP_PROVIDER_TOKEN?: string;
  WHATSAPP_PHONE_NUMBER_ID?: string;
  EMAIL_PROVIDER_URL?: string;
  EMAIL_PROVIDER_TOKEN?: string;
  NOTIFICATION_AUTOMATION_SECRET?: string;
  NOTIFICATION_PROVIDER_WEBHOOK_SECRET?: string;
};

function readEnv(): Env {
  const missing = required.filter((key) => !process.env[key]);

  if (missing.length > 0) {
    throw new Error(`Missing required env vars: ${missing.join(", ")}`);
  }

  return {
    NODE_ENV: process.env.NODE_ENV ?? "development",
    PORT: Number(process.env.PORT ?? 3333),
    APP_URL: process.env.APP_URL ?? "http://localhost:5173",
    FRONTEND_URL: process.env.FRONTEND_URL,
    CORS_ORIGIN: process.env.CORS_ORIGIN,
    SUPABASE_URL: process.env.SUPABASE_URL!,
    SUPABASE_ANON_KEY: process.env.SUPABASE_ANON_KEY!,
    SUPABASE_SERVICE_ROLE_KEY: process.env.SUPABASE_SERVICE_ROLE_KEY!,
    DATABASE_URL: process.env.DATABASE_URL,
    IMOBIFLOW_LOCAL_DEV_AUTH: process.env.IMOBIFLOW_LOCAL_DEV_AUTH,
    IMOBIFLOW_LOCAL_DEV_TOKEN: process.env.IMOBIFLOW_LOCAL_DEV_TOKEN,
    IMOBIFLOW_LOCAL_DEV_COMPANY_ID: process.env.IMOBIFLOW_LOCAL_DEV_COMPANY_ID,
    IMOBIFLOW_LOCAL_DEV_USER_ID: process.env.IMOBIFLOW_LOCAL_DEV_USER_ID,
    IMOBIFLOW_LOCAL_DEV_ROLE: process.env.IMOBIFLOW_LOCAL_DEV_ROLE,
    IMOBIFLOW_AUTH_PROVIDER: process.env.IMOBIFLOW_AUTH_PROVIDER,
    IMOBIFLOW_MYSQL_AUTH: process.env.IMOBIFLOW_MYSQL_AUTH,
    IMOBIFLOW_BOOTSTRAP_EMAIL: process.env.IMOBIFLOW_BOOTSTRAP_EMAIL,
    IMOBIFLOW_BOOTSTRAP_PASSWORD: process.env.IMOBIFLOW_BOOTSTRAP_PASSWORD,
    IMOBIFLOW_BOOTSTRAP_COMPANY_NAME: process.env.IMOBIFLOW_BOOTSTRAP_COMPANY_NAME,
    JWT_SECRET: process.env.JWT_SECRET,
    AUTH_EXPOSE_TEST_TOKENS: process.env.AUTH_EXPOSE_TEST_TOKENS,
    BILLING_PROVIDER: process.env.BILLING_PROVIDER,
    BILLING_PAST_DUE_GRACE_DAYS: process.env.BILLING_PAST_DUE_GRACE_DAYS,
    ALLOW_SYNTHETIC_BILLING_PROVISIONING: process.env.ALLOW_SYNTHETIC_BILLING_PROVISIONING,
    SYNTHETIC_BILLING_ADMIN_SECRET: process.env.SYNTHETIC_BILLING_ADMIN_SECRET,
    STORAGE_PROVIDER: process.env.STORAGE_PROVIDER,
    CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
    CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
    CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
    CLOUDINARY_UPLOAD_FOLDER: process.env.CLOUDINARY_UPLOAD_FOLDER,
    CLOUDINARY_UPLOAD_PRESET: process.env.CLOUDINARY_UPLOAD_PRESET,
    IMPORT_MEDIA_CONCURRENCY: process.env.IMPORT_MEDIA_CONCURRENCY,
    IMPORT_METRICS_ENABLED: process.env.IMPORT_METRICS_ENABLED,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
    R2_ACCESS_KEY_ID: process.env.R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY: process.env.R2_SECRET_ACCESS_KEY,
    R2_BUCKET: process.env.R2_BUCKET,
    R2_PUBLIC_BASE_URL: process.env.R2_PUBLIC_BASE_URL,
    KIWIFY_WEBHOOK_SECRET: process.env.KIWIFY_WEBHOOK_SECRET,
    CAKTO_WEBHOOK_SECRET: process.env.CAKTO_WEBHOOK_SECRET,
    PAYMENT_GATEWAY_WEBHOOK_SECRET: process.env.PAYMENT_GATEWAY_WEBHOOK_SECRET,
    IUGU_API_KEY: process.env.IUGU_API_KEY,
    IUGU_WEBHOOK_SECRET: process.env.IUGU_WEBHOOK_SECRET,
    PJBANK_API_KEY: process.env.PJBANK_API_KEY,
    PJBANK_WEBHOOK_SECRET: process.env.PJBANK_WEBHOOK_SECRET,
    ASAAS_API_KEY: process.env.ASAAS_API_KEY,
    ASAAS_WEBHOOK_SECRET: process.env.ASAAS_WEBHOOK_SECRET,
    PORTAL_INTEGRATIONS_WEBHOOK_SECRET: process.env.PORTAL_INTEGRATIONS_WEBHOOK_SECRET,
    STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY,
    STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET,
    GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
    GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
    GOOGLE_MAPS_API_KEY: process.env.GOOGLE_MAPS_API_KEY,
    ZAP_IMOVEIS_CLIENT_ID: process.env.ZAP_IMOVEIS_CLIENT_ID,
    ZAP_IMOVEIS_CLIENT_SECRET: process.env.ZAP_IMOVEIS_CLIENT_SECRET,
    OLX_CLIENT_ID: process.env.OLX_CLIENT_ID,
    OLX_CLIENT_SECRET: process.env.OLX_CLIENT_SECRET,
    VIVA_REAL_CLIENT_ID: process.env.VIVA_REAL_CLIENT_ID,
    VIVA_REAL_CLIENT_SECRET: process.env.VIVA_REAL_CLIENT_SECRET,
    RECEITA_FEDERAL_API_KEY: process.env.RECEITA_FEDERAL_API_KEY,
    RECEITA_FEDERAL_BASE_URL: process.env.RECEITA_FEDERAL_BASE_URL,
    WHATSAPP_PROVIDER_URL: process.env.WHATSAPP_PROVIDER_URL,
    WHATSAPP_PROVIDER_TOKEN: process.env.WHATSAPP_PROVIDER_TOKEN,
    WHATSAPP_PHONE_NUMBER_ID: process.env.WHATSAPP_PHONE_NUMBER_ID,
    EMAIL_PROVIDER_URL: process.env.EMAIL_PROVIDER_URL,
    EMAIL_PROVIDER_TOKEN: process.env.EMAIL_PROVIDER_TOKEN,
    NOTIFICATION_AUTOMATION_SECRET: process.env.NOTIFICATION_AUTOMATION_SECRET,
    NOTIFICATION_PROVIDER_WEBHOOK_SECRET: process.env.NOTIFICATION_PROVIDER_WEBHOOK_SECRET,
  };
}

export const env = readEnv();
