CREATE TABLE IF NOT EXISTS `stored_files` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `entity_type` VARCHAR(80) NOT NULL,
  `entity_id` CHAR(36) NOT NULL,
  `provider` VARCHAR(60) NOT NULL,
  `public_id` VARCHAR(700) NOT NULL,
  `resource_type` VARCHAR(40) NOT NULL,
  `secure_url` VARCHAR(1200) NOT NULL,
  `original_filename` VARCHAR(240) NOT NULL,
  `mime_type` VARCHAR(120) NOT NULL,
  `size_bytes` INT NULL,
  `width` INT NULL,
  `height` INT NULL,
  `format` VARCHAR(40) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `uploaded_by` CHAR(36) NULL,
  `is_test_data` BOOLEAN NOT NULL DEFAULT false,
  `test_batch_id` VARCHAR(120) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `stored_files_provider_public_id_key` (`provider`, `public_id`),
  KEY `stored_files_company_id_entity_type_entity_id_idx` (`company_id`, `entity_type`, `entity_id`),
  KEY `stored_files_company_id_is_test_data_test_batch_id_idx` (`company_id`, `is_test_data`, `test_batch_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
