/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadosRouteImport } from './routes/resultados'
import { Route as QuemUsaRouteImport } from './routes/quem-usa'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as InteligenciaRouteImport } from './routes/inteligencia'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AssinaturaBloqueadaRouteImport } from './routes/assinatura-bloqueada'
import { Route as AppRouteImport } from './routes/app'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as SiteSlugRouteImport } from './routes/site.$slug'
import { Route as AssinarVistoriaTokenRouteImport } from './routes/assinar-vistoria.$token'
import { Route as AppVistoriasRouteImport } from './routes/app.vistorias'
import { Route as AppTestesRouteImport } from './routes/app.testes'
import { Route as AppSiteRouteImport } from './routes/app.site'
import { Route as AppProprietariosRouteImport } from './routes/app.proprietarios'
import { Route as AppOperacoesRouteImport } from './routes/app.operacoes'
import { Route as AppNotificacoesRouteImport } from './routes/app.notificacoes'
import { Route as AppInteligenciaRouteImport } from './routes/app.inteligencia'
import { Route as AppIntegracoesRouteImport } from './routes/app.integracoes'
import { Route as AppImportacoesRouteImport } from './routes/app.importacoes'
import { Route as AppImoveisRouteImport } from './routes/app.imoveis'
import { Route as AppFinanceiroRouteImport } from './routes/app.financeiro'
import { Route as AppCustosRouteImport } from './routes/app.custos'
import { Route as AppCrmRouteImport } from './routes/app.crm'
import { Route as AppContratosRouteImport } from './routes/app.contratos'
import { Route as AppConfiguracoesRouteImport } from './routes/app.configuracoes'
import { Route as AppAgendaRouteImport } from './routes/app.agenda'
import { Route as PortalProprietarioTokenRouteImport } from './routes/portal.proprietario.$token'
import { Route as PortalInquilinoTokenRouteImport } from './routes/portal.inquilino.$token'
import { Route as AppVistoriasInspectionIdRouteImport } from './routes/app.vistorias.$inspectionId'
import { Route as AppSiteBuilderRouteImport } from './routes/app.site.builder'
import { Route as SiteSlugImoveisPropertySlugRouteImport } from './routes/site.$slug.imoveis.$propertySlug'
import { Route as AppSiteBuilderPreviewWebsiteIdRouteImport } from './routes/app.site.builder.preview.$websiteId'
import { Route as AppSiteBuilderEditorWebsiteIdRouteImport } from './routes/app.site.builder.editor.$websiteId'
import { Route as AppSiteBuilderEditorWebsiteIdCodeRouteImport } from './routes/app.site.builder.editor.$websiteId.code'
import { Route as AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRouteImport } from './routes/app.site.builder.preview.$websiteId.imovel.$propertySlug'

const ResultadosRoute = ResultadosRouteImport.update({
  id: '/resultados',
  path: '/resultados',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemUsaRoute = QuemUsaRouteImport.update({
  id: '/quem-usa',
  path: '/quem-usa',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaRoute = InteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaBloqueadaRoute = AssinaturaBloqueadaRouteImport.update({
  id: '/assinatura-bloqueada',
  path: '/assinatura-bloqueada',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SiteSlugRoute = SiteSlugRouteImport.update({
  id: '/site/$slug',
  path: '/site/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarVistoriaTokenRoute = AssinarVistoriaTokenRouteImport.update({
  id: '/assinar-vistoria/$token',
  path: '/assinar-vistoria/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVistoriasRoute = AppVistoriasRouteImport.update({
  id: '/vistorias',
  path: '/vistorias',
  getParentRoute: () => AppRoute,
} as any)
const AppTestesRoute = AppTestesRouteImport.update({
  id: '/testes',
  path: '/testes',
  getParentRoute: () => AppRoute,
} as any)
const AppSiteRoute = AppSiteRouteImport.update({
  id: '/site',
  path: '/site',
  getParentRoute: () => AppRoute,
} as any)
const AppProprietariosRoute = AppProprietariosRouteImport.update({
  id: '/proprietarios',
  path: '/proprietarios',
  getParentRoute: () => AppRoute,
} as any)
const AppOperacoesRoute = AppOperacoesRouteImport.update({
  id: '/operacoes',
  path: '/operacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificacoesRoute = AppNotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppInteligenciaRoute = AppInteligenciaRouteImport.update({
  id: '/inteligencia',
  path: '/inteligencia',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegracoesRoute = AppIntegracoesRouteImport.update({
  id: '/integracoes',
  path: '/integracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImportacoesRoute = AppImportacoesRouteImport.update({
  id: '/importacoes',
  path: '/importacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppImoveisRoute = AppImoveisRouteImport.update({
  id: '/imoveis',
  path: '/imoveis',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppCustosRoute = AppCustosRouteImport.update({
  id: '/custos',
  path: '/custos',
  getParentRoute: () => AppRoute,
} as any)
const AppCrmRoute = AppCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AppRoute,
} as any)
const AppContratosRoute = AppContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => AppRoute,
} as any)
const AppConfiguracoesRoute = AppConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const PortalProprietarioTokenRoute = PortalProprietarioTokenRouteImport.update({
  id: '/portal/proprietario/$token',
  path: '/portal/proprietario/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalInquilinoTokenRoute = PortalInquilinoTokenRouteImport.update({
  id: '/portal/inquilino/$token',
  path: '/portal/inquilino/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppVistoriasInspectionIdRoute =
  AppVistoriasInspectionIdRouteImport.update({
    id: '/$inspectionId',
    path: '/$inspectionId',
    getParentRoute: () => AppVistoriasRoute,
  } as any)
const AppSiteBuilderRoute = AppSiteBuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => AppSiteRoute,
} as any)
const SiteSlugImoveisPropertySlugRoute =
  SiteSlugImoveisPropertySlugRouteImport.update({
    id: '/imoveis/$propertySlug',
    path: '/imoveis/$propertySlug',
    getParentRoute: () => SiteSlugRoute,
  } as any)
const AppSiteBuilderPreviewWebsiteIdRoute =
  AppSiteBuilderPreviewWebsiteIdRouteImport.update({
    id: '/preview/$websiteId',
    path: '/preview/$websiteId',
    getParentRoute: () => AppSiteBuilderRoute,
  } as any)
const AppSiteBuilderEditorWebsiteIdRoute =
  AppSiteBuilderEditorWebsiteIdRouteImport.update({
    id: '/editor/$websiteId',
    path: '/editor/$websiteId',
    getParentRoute: () => AppSiteBuilderRoute,
  } as any)
const AppSiteBuilderEditorWebsiteIdCodeRoute =
  AppSiteBuilderEditorWebsiteIdCodeRouteImport.update({
    id: '/code',
    path: '/code',
    getParentRoute: () => AppSiteBuilderEditorWebsiteIdRoute,
  } as any)
const AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute =
  AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRouteImport.update({
    id: '/imovel/$propertySlug',
    path: '/imovel/$propertySlug',
    getParentRoute: () => AppSiteBuilderPreviewWebsiteIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/app': typeof AppRouteWithChildren
  '/assinatura-bloqueada': typeof AssinaturaBloqueadaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/inteligencia': typeof InteligenciaRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/quem-usa': typeof QuemUsaRoute
  '/resultados': typeof ResultadosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/custos': typeof AppCustosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/operacoes': typeof AppOperacoesRoute
  '/app/proprietarios': typeof AppProprietariosRoute
  '/app/site': typeof AppSiteRouteWithChildren
  '/app/testes': typeof AppTestesRoute
  '/app/vistorias': typeof AppVistoriasRouteWithChildren
  '/assinar-vistoria/$token': typeof AssinarVistoriaTokenRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/site/builder': typeof AppSiteBuilderRouteWithChildren
  '/app/vistorias/$inspectionId': typeof AppVistoriasInspectionIdRoute
  '/portal/inquilino/$token': typeof PortalInquilinoTokenRoute
  '/portal/proprietario/$token': typeof PortalProprietarioTokenRoute
  '/site/$slug/imoveis/$propertySlug': typeof SiteSlugImoveisPropertySlugRoute
  '/app/site/builder/editor/$websiteId': typeof AppSiteBuilderEditorWebsiteIdRouteWithChildren
  '/app/site/builder/preview/$websiteId': typeof AppSiteBuilderPreviewWebsiteIdRouteWithChildren
  '/app/site/builder/editor/$websiteId/code': typeof AppSiteBuilderEditorWebsiteIdCodeRoute
  '/app/site/builder/preview/$websiteId/imovel/$propertySlug': typeof AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/assinatura-bloqueada': typeof AssinaturaBloqueadaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/inteligencia': typeof InteligenciaRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/quem-usa': typeof QuemUsaRoute
  '/resultados': typeof ResultadosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/custos': typeof AppCustosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/operacoes': typeof AppOperacoesRoute
  '/app/proprietarios': typeof AppProprietariosRoute
  '/app/site': typeof AppSiteRouteWithChildren
  '/app/testes': typeof AppTestesRoute
  '/app/vistorias': typeof AppVistoriasRouteWithChildren
  '/assinar-vistoria/$token': typeof AssinarVistoriaTokenRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/site/builder': typeof AppSiteBuilderRouteWithChildren
  '/app/vistorias/$inspectionId': typeof AppVistoriasInspectionIdRoute
  '/portal/inquilino/$token': typeof PortalInquilinoTokenRoute
  '/portal/proprietario/$token': typeof PortalProprietarioTokenRoute
  '/site/$slug/imoveis/$propertySlug': typeof SiteSlugImoveisPropertySlugRoute
  '/app/site/builder/editor/$websiteId': typeof AppSiteBuilderEditorWebsiteIdRouteWithChildren
  '/app/site/builder/preview/$websiteId': typeof AppSiteBuilderPreviewWebsiteIdRouteWithChildren
  '/app/site/builder/editor/$websiteId/code': typeof AppSiteBuilderEditorWebsiteIdCodeRoute
  '/app/site/builder/preview/$websiteId/imovel/$propertySlug': typeof AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/app': typeof AppRouteWithChildren
  '/assinatura-bloqueada': typeof AssinaturaBloqueadaRoute
  '/cadastro': typeof CadastroRoute
  '/entrar': typeof EntrarRoute
  '/faq': typeof FaqRoute
  '/inteligencia': typeof InteligenciaRoute
  '/planos': typeof PlanosRoute
  '/produto': typeof ProdutoRoute
  '/quem-usa': typeof QuemUsaRoute
  '/resultados': typeof ResultadosRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/configuracoes': typeof AppConfiguracoesRoute
  '/app/contratos': typeof AppContratosRoute
  '/app/crm': typeof AppCrmRoute
  '/app/custos': typeof AppCustosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/imoveis': typeof AppImoveisRoute
  '/app/importacoes': typeof AppImportacoesRoute
  '/app/integracoes': typeof AppIntegracoesRoute
  '/app/inteligencia': typeof AppInteligenciaRoute
  '/app/notificacoes': typeof AppNotificacoesRoute
  '/app/operacoes': typeof AppOperacoesRoute
  '/app/proprietarios': typeof AppProprietariosRoute
  '/app/site': typeof AppSiteRouteWithChildren
  '/app/testes': typeof AppTestesRoute
  '/app/vistorias': typeof AppVistoriasRouteWithChildren
  '/assinar-vistoria/$token': typeof AssinarVistoriaTokenRoute
  '/site/$slug': typeof SiteSlugRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/site/builder': typeof AppSiteBuilderRouteWithChildren
  '/app/vistorias/$inspectionId': typeof AppVistoriasInspectionIdRoute
  '/portal/inquilino/$token': typeof PortalInquilinoTokenRoute
  '/portal/proprietario/$token': typeof PortalProprietarioTokenRoute
  '/site/$slug/imoveis/$propertySlug': typeof SiteSlugImoveisPropertySlugRoute
  '/app/site/builder/editor/$websiteId': typeof AppSiteBuilderEditorWebsiteIdRouteWithChildren
  '/app/site/builder/preview/$websiteId': typeof AppSiteBuilderPreviewWebsiteIdRouteWithChildren
  '/app/site/builder/editor/$websiteId/code': typeof AppSiteBuilderEditorWebsiteIdCodeRoute
  '/app/site/builder/preview/$websiteId/imovel/$propertySlug': typeof AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/aceitar-convite'
    | '/app'
    | '/assinatura-bloqueada'
    | '/cadastro'
    | '/entrar'
    | '/faq'
    | '/inteligencia'
    | '/planos'
    | '/produto'
    | '/quem-usa'
    | '/resultados'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/custos'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/importacoes'
    | '/app/integracoes'
    | '/app/inteligencia'
    | '/app/notificacoes'
    | '/app/operacoes'
    | '/app/proprietarios'
    | '/app/site'
    | '/app/testes'
    | '/app/vistorias'
    | '/assinar-vistoria/$token'
    | '/site/$slug'
    | '/app/'
    | '/app/site/builder'
    | '/app/vistorias/$inspectionId'
    | '/portal/inquilino/$token'
    | '/portal/proprietario/$token'
    | '/site/$slug/imoveis/$propertySlug'
    | '/app/site/builder/editor/$websiteId'
    | '/app/site/builder/preview/$websiteId'
    | '/app/site/builder/editor/$websiteId/code'
    | '/app/site/builder/preview/$websiteId/imovel/$propertySlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/aceitar-convite'
    | '/assinatura-bloqueada'
    | '/cadastro'
    | '/entrar'
    | '/faq'
    | '/inteligencia'
    | '/planos'
    | '/produto'
    | '/quem-usa'
    | '/resultados'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/custos'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/importacoes'
    | '/app/integracoes'
    | '/app/inteligencia'
    | '/app/notificacoes'
    | '/app/operacoes'
    | '/app/proprietarios'
    | '/app/site'
    | '/app/testes'
    | '/app/vistorias'
    | '/assinar-vistoria/$token'
    | '/site/$slug'
    | '/app'
    | '/app/site/builder'
    | '/app/vistorias/$inspectionId'
    | '/portal/inquilino/$token'
    | '/portal/proprietario/$token'
    | '/site/$slug/imoveis/$propertySlug'
    | '/app/site/builder/editor/$websiteId'
    | '/app/site/builder/preview/$websiteId'
    | '/app/site/builder/editor/$websiteId/code'
    | '/app/site/builder/preview/$websiteId/imovel/$propertySlug'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/aceitar-convite'
    | '/app'
    | '/assinatura-bloqueada'
    | '/cadastro'
    | '/entrar'
    | '/faq'
    | '/inteligencia'
    | '/planos'
    | '/produto'
    | '/quem-usa'
    | '/resultados'
    | '/app/agenda'
    | '/app/configuracoes'
    | '/app/contratos'
    | '/app/crm'
    | '/app/custos'
    | '/app/financeiro'
    | '/app/imoveis'
    | '/app/importacoes'
    | '/app/integracoes'
    | '/app/inteligencia'
    | '/app/notificacoes'
    | '/app/operacoes'
    | '/app/proprietarios'
    | '/app/site'
    | '/app/testes'
    | '/app/vistorias'
    | '/assinar-vistoria/$token'
    | '/site/$slug'
    | '/app/'
    | '/app/site/builder'
    | '/app/vistorias/$inspectionId'
    | '/portal/inquilino/$token'
    | '/portal/proprietario/$token'
    | '/site/$slug/imoveis/$propertySlug'
    | '/app/site/builder/editor/$websiteId'
    | '/app/site/builder/preview/$websiteId'
    | '/app/site/builder/editor/$websiteId/code'
    | '/app/site/builder/preview/$websiteId/imovel/$propertySlug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AceitarConviteRoute: typeof AceitarConviteRoute
  AppRoute: typeof AppRouteWithChildren
  AssinaturaBloqueadaRoute: typeof AssinaturaBloqueadaRoute
  CadastroRoute: typeof CadastroRoute
  EntrarRoute: typeof EntrarRoute
  FaqRoute: typeof FaqRoute
  InteligenciaRoute: typeof InteligenciaRoute
  PlanosRoute: typeof PlanosRoute
  ProdutoRoute: typeof ProdutoRoute
  QuemUsaRoute: typeof QuemUsaRoute
  ResultadosRoute: typeof ResultadosRoute
  AssinarVistoriaTokenRoute: typeof AssinarVistoriaTokenRoute
  SiteSlugRoute: typeof SiteSlugRouteWithChildren
  PortalInquilinoTokenRoute: typeof PortalInquilinoTokenRoute
  PortalProprietarioTokenRoute: typeof PortalProprietarioTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultados': {
      id: '/resultados'
      path: '/resultados'
      fullPath: '/resultados'
      preLoaderRoute: typeof ResultadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-usa': {
      id: '/quem-usa'
      path: '/quem-usa'
      fullPath: '/quem-usa'
      preLoaderRoute: typeof QuemUsaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia': {
      id: '/inteligencia'
      path: '/inteligencia'
      fullPath: '/inteligencia'
      preLoaderRoute: typeof InteligenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-bloqueada': {
      id: '/assinatura-bloqueada'
      path: '/assinatura-bloqueada'
      fullPath: '/assinatura-bloqueada'
      preLoaderRoute: typeof AssinaturaBloqueadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/site/$slug': {
      id: '/site/$slug'
      path: '/site/$slug'
      fullPath: '/site/$slug'
      preLoaderRoute: typeof SiteSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar-vistoria/$token': {
      id: '/assinar-vistoria/$token'
      path: '/assinar-vistoria/$token'
      fullPath: '/assinar-vistoria/$token'
      preLoaderRoute: typeof AssinarVistoriaTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vistorias': {
      id: '/app/vistorias'
      path: '/vistorias'
      fullPath: '/app/vistorias'
      preLoaderRoute: typeof AppVistoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/testes': {
      id: '/app/testes'
      path: '/testes'
      fullPath: '/app/testes'
      preLoaderRoute: typeof AppTestesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/site': {
      id: '/app/site'
      path: '/site'
      fullPath: '/app/site'
      preLoaderRoute: typeof AppSiteRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/proprietarios': {
      id: '/app/proprietarios'
      path: '/proprietarios'
      fullPath: '/app/proprietarios'
      preLoaderRoute: typeof AppProprietariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/operacoes': {
      id: '/app/operacoes'
      path: '/operacoes'
      fullPath: '/app/operacoes'
      preLoaderRoute: typeof AppOperacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notificacoes': {
      id: '/app/notificacoes'
      path: '/notificacoes'
      fullPath: '/app/notificacoes'
      preLoaderRoute: typeof AppNotificacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inteligencia': {
      id: '/app/inteligencia'
      path: '/inteligencia'
      fullPath: '/app/inteligencia'
      preLoaderRoute: typeof AppInteligenciaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integracoes': {
      id: '/app/integracoes'
      path: '/integracoes'
      fullPath: '/app/integracoes'
      preLoaderRoute: typeof AppIntegracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/importacoes': {
      id: '/app/importacoes'
      path: '/importacoes'
      fullPath: '/app/importacoes'
      preLoaderRoute: typeof AppImportacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/imoveis': {
      id: '/app/imoveis'
      path: '/imoveis'
      fullPath: '/app/imoveis'
      preLoaderRoute: typeof AppImoveisRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/custos': {
      id: '/app/custos'
      path: '/custos'
      fullPath: '/app/custos'
      preLoaderRoute: typeof AppCustosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/crm': {
      id: '/app/crm'
      path: '/crm'
      fullPath: '/app/crm'
      preLoaderRoute: typeof AppCrmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/contratos': {
      id: '/app/contratos'
      path: '/contratos'
      fullPath: '/app/contratos'
      preLoaderRoute: typeof AppContratosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/configuracoes': {
      id: '/app/configuracoes'
      path: '/configuracoes'
      fullPath: '/app/configuracoes'
      preLoaderRoute: typeof AppConfiguracoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/portal/proprietario/$token': {
      id: '/portal/proprietario/$token'
      path: '/portal/proprietario/$token'
      fullPath: '/portal/proprietario/$token'
      preLoaderRoute: typeof PortalProprietarioTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/inquilino/$token': {
      id: '/portal/inquilino/$token'
      path: '/portal/inquilino/$token'
      fullPath: '/portal/inquilino/$token'
      preLoaderRoute: typeof PortalInquilinoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/vistorias/$inspectionId': {
      id: '/app/vistorias/$inspectionId'
      path: '/$inspectionId'
      fullPath: '/app/vistorias/$inspectionId'
      preLoaderRoute: typeof AppVistoriasInspectionIdRouteImport
      parentRoute: typeof AppVistoriasRoute
    }
    '/app/site/builder': {
      id: '/app/site/builder'
      path: '/builder'
      fullPath: '/app/site/builder'
      preLoaderRoute: typeof AppSiteBuilderRouteImport
      parentRoute: typeof AppSiteRoute
    }
    '/site/$slug/imoveis/$propertySlug': {
      id: '/site/$slug/imoveis/$propertySlug'
      path: '/imoveis/$propertySlug'
      fullPath: '/site/$slug/imoveis/$propertySlug'
      preLoaderRoute: typeof SiteSlugImoveisPropertySlugRouteImport
      parentRoute: typeof SiteSlugRoute
    }
    '/app/site/builder/preview/$websiteId': {
      id: '/app/site/builder/preview/$websiteId'
      path: '/preview/$websiteId'
      fullPath: '/app/site/builder/preview/$websiteId'
      preLoaderRoute: typeof AppSiteBuilderPreviewWebsiteIdRouteImport
      parentRoute: typeof AppSiteBuilderRoute
    }
    '/app/site/builder/editor/$websiteId': {
      id: '/app/site/builder/editor/$websiteId'
      path: '/editor/$websiteId'
      fullPath: '/app/site/builder/editor/$websiteId'
      preLoaderRoute: typeof AppSiteBuilderEditorWebsiteIdRouteImport
      parentRoute: typeof AppSiteBuilderRoute
    }
    '/app/site/builder/editor/$websiteId/code': {
      id: '/app/site/builder/editor/$websiteId/code'
      path: '/code'
      fullPath: '/app/site/builder/editor/$websiteId/code'
      preLoaderRoute: typeof AppSiteBuilderEditorWebsiteIdCodeRouteImport
      parentRoute: typeof AppSiteBuilderEditorWebsiteIdRoute
    }
    '/app/site/builder/preview/$websiteId/imovel/$propertySlug': {
      id: '/app/site/builder/preview/$websiteId/imovel/$propertySlug'
      path: '/imovel/$propertySlug'
      fullPath: '/app/site/builder/preview/$websiteId/imovel/$propertySlug'
      preLoaderRoute: typeof AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRouteImport
      parentRoute: typeof AppSiteBuilderPreviewWebsiteIdRoute
    }
  }
}

interface AppSiteBuilderEditorWebsiteIdRouteChildren {
  AppSiteBuilderEditorWebsiteIdCodeRoute: typeof AppSiteBuilderEditorWebsiteIdCodeRoute
}

const AppSiteBuilderEditorWebsiteIdRouteChildren: AppSiteBuilderEditorWebsiteIdRouteChildren =
  {
    AppSiteBuilderEditorWebsiteIdCodeRoute:
      AppSiteBuilderEditorWebsiteIdCodeRoute,
  }

const AppSiteBuilderEditorWebsiteIdRouteWithChildren =
  AppSiteBuilderEditorWebsiteIdRoute._addFileChildren(
    AppSiteBuilderEditorWebsiteIdRouteChildren,
  )

interface AppSiteBuilderPreviewWebsiteIdRouteChildren {
  AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute: typeof AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute
}

const AppSiteBuilderPreviewWebsiteIdRouteChildren: AppSiteBuilderPreviewWebsiteIdRouteChildren =
  {
    AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute:
      AppSiteBuilderPreviewWebsiteIdImovelPropertySlugRoute,
  }

const AppSiteBuilderPreviewWebsiteIdRouteWithChildren =
  AppSiteBuilderPreviewWebsiteIdRoute._addFileChildren(
    AppSiteBuilderPreviewWebsiteIdRouteChildren,
  )

interface AppSiteBuilderRouteChildren {
  AppSiteBuilderEditorWebsiteIdRoute: typeof AppSiteBuilderEditorWebsiteIdRouteWithChildren
  AppSiteBuilderPreviewWebsiteIdRoute: typeof AppSiteBuilderPreviewWebsiteIdRouteWithChildren
}

const AppSiteBuilderRouteChildren: AppSiteBuilderRouteChildren = {
  AppSiteBuilderEditorWebsiteIdRoute:
    AppSiteBuilderEditorWebsiteIdRouteWithChildren,
  AppSiteBuilderPreviewWebsiteIdRoute:
    AppSiteBuilderPreviewWebsiteIdRouteWithChildren,
}

const AppSiteBuilderRouteWithChildren = AppSiteBuilderRoute._addFileChildren(
  AppSiteBuilderRouteChildren,
)

interface AppSiteRouteChildren {
  AppSiteBuilderRoute: typeof AppSiteBuilderRouteWithChildren
}

const AppSiteRouteChildren: AppSiteRouteChildren = {
  AppSiteBuilderRoute: AppSiteBuilderRouteWithChildren,
}

const AppSiteRouteWithChildren =
  AppSiteRoute._addFileChildren(AppSiteRouteChildren)

interface AppVistoriasRouteChildren {
  AppVistoriasInspectionIdRoute: typeof AppVistoriasInspectionIdRoute
}

const AppVistoriasRouteChildren: AppVistoriasRouteChildren = {
  AppVistoriasInspectionIdRoute: AppVistoriasInspectionIdRoute,
}

const AppVistoriasRouteWithChildren = AppVistoriasRoute._addFileChildren(
  AppVistoriasRouteChildren,
)

interface AppRouteChildren {
  AppAgendaRoute: typeof AppAgendaRoute
  AppConfiguracoesRoute: typeof AppConfiguracoesRoute
  AppContratosRoute: typeof AppContratosRoute
  AppCrmRoute: typeof AppCrmRoute
  AppCustosRoute: typeof AppCustosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppImoveisRoute: typeof AppImoveisRoute
  AppImportacoesRoute: typeof AppImportacoesRoute
  AppIntegracoesRoute: typeof AppIntegracoesRoute
  AppInteligenciaRoute: typeof AppInteligenciaRoute
  AppNotificacoesRoute: typeof AppNotificacoesRoute
  AppOperacoesRoute: typeof AppOperacoesRoute
  AppProprietariosRoute: typeof AppProprietariosRoute
  AppSiteRoute: typeof AppSiteRouteWithChildren
  AppTestesRoute: typeof AppTestesRoute
  AppVistoriasRoute: typeof AppVistoriasRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgendaRoute: AppAgendaRoute,
  AppConfiguracoesRoute: AppConfiguracoesRoute,
  AppContratosRoute: AppContratosRoute,
  AppCrmRoute: AppCrmRoute,
  AppCustosRoute: AppCustosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppImoveisRoute: AppImoveisRoute,
  AppImportacoesRoute: AppImportacoesRoute,
  AppIntegracoesRoute: AppIntegracoesRoute,
  AppInteligenciaRoute: AppInteligenciaRoute,
  AppNotificacoesRoute: AppNotificacoesRoute,
  AppOperacoesRoute: AppOperacoesRoute,
  AppProprietariosRoute: AppProprietariosRoute,
  AppSiteRoute: AppSiteRouteWithChildren,
  AppTestesRoute: AppTestesRoute,
  AppVistoriasRoute: AppVistoriasRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface SiteSlugRouteChildren {
  SiteSlugImoveisPropertySlugRoute: typeof SiteSlugImoveisPropertySlugRoute
}

const SiteSlugRouteChildren: SiteSlugRouteChildren = {
  SiteSlugImoveisPropertySlugRoute: SiteSlugImoveisPropertySlugRoute,
}

const SiteSlugRouteWithChildren = SiteSlugRoute._addFileChildren(
  SiteSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AceitarConviteRoute: AceitarConviteRoute,
  AppRoute: AppRouteWithChildren,
  AssinaturaBloqueadaRoute: AssinaturaBloqueadaRoute,
  CadastroRoute: CadastroRoute,
  EntrarRoute: EntrarRoute,
  FaqRoute: FaqRoute,
  InteligenciaRoute: InteligenciaRoute,
  PlanosRoute: PlanosRoute,
  ProdutoRoute: ProdutoRoute,
  QuemUsaRoute: QuemUsaRoute,
  ResultadosRoute: ResultadosRoute,
  AssinarVistoriaTokenRoute: AssinarVistoriaTokenRoute,
  SiteSlugRoute: SiteSlugRouteWithChildren,
  PortalInquilinoTokenRoute: PortalInquilinoTokenRoute,
  PortalProprietarioTokenRoute: PortalProprietarioTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
