/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjudaRouteImport } from './routes/ajuda'
import { Route as ApiDocsRouteImport } from './routes/api-docs'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CarreirasRouteImport } from './routes/carreiras'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as ContratoRouteImport } from './routes/contrato'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ImprensaRouteImport } from './routes/imprensa'
import { Route as IndiqueRouteImport } from './routes/indique'
import { Route as InteligenciaIaRouteImport } from './routes/inteligencia-ia'
import { Route as LgpdRouteImport } from './routes/lgpd'
import { Route as ParaCorretoresRouteImport } from './routes/para-corretores'
import { Route as ParaGestoresRouteImport } from './routes/para-gestores'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProdutoRouteImport } from './routes/produto'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as StatusRouteImport } from './routes/status'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as VistoriaRouteImport } from './routes/vistoria'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjudaRoute = AjudaRouteImport.update({
  id: '/ajuda',
  path: '/ajuda',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDocsRoute = ApiDocsRouteImport.update({
  id: '/api-docs',
  path: '/api-docs',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CarreirasRoute = CarreirasRouteImport.update({
  id: '/carreiras',
  path: '/carreiras',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ContratoRoute = ContratoRouteImport.update({
  id: '/contrato',
  path: '/contrato',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprensaRoute = ImprensaRouteImport.update({
  id: '/imprensa',
  path: '/imprensa',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiqueRoute = IndiqueRouteImport.update({
  id: '/indique',
  path: '/indique',
  getParentRoute: () => rootRouteImport,
} as any)
const InteligenciaIaRoute = InteligenciaIaRouteImport.update({
  id: '/inteligencia-ia',
  path: '/inteligencia-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const LgpdRoute = LgpdRouteImport.update({
  id: '/lgpd',
  path: '/lgpd',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaCorretoresRoute = ParaCorretoresRouteImport.update({
  id: '/para-corretores',
  path: '/para-corretores',
  getParentRoute: () => rootRouteImport,
} as any)
const ParaGestoresRoute = ParaGestoresRouteImport.update({
  id: '/para-gestores',
  path: '/para-gestores',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoRoute = ProdutoRouteImport.update({
  id: '/produto',
  path: '/produto',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const VistoriaRoute = VistoriaRouteImport.update({
  id: '/vistoria',
  path: '/vistoria',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/carreiras': typeof CarreirasRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/docs': typeof DocsRoute
  '/imprensa': typeof ImprensaRoute
  '/indique': typeof IndiqueRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/lgpd': typeof LgpdRoute
  '/para-corretores': typeof ParaCorretoresRoute
  '/para-gestores': typeof ParaGestoresRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/vistoria': typeof VistoriaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/carreiras': typeof CarreirasRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/docs': typeof DocsRoute
  '/imprensa': typeof ImprensaRoute
  '/indique': typeof IndiqueRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/lgpd': typeof LgpdRoute
  '/para-corretores': typeof ParaCorretoresRoute
  '/para-gestores': typeof ParaGestoresRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/vistoria': typeof VistoriaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajuda': typeof AjudaRoute
  '/api-docs': typeof ApiDocsRoute
  '/blog': typeof BlogRoute
  '/carreiras': typeof CarreirasRoute
  '/clientes': typeof ClientesRoute
  '/contrato': typeof ContratoRoute
  '/docs': typeof DocsRoute
  '/imprensa': typeof ImprensaRoute
  '/indique': typeof IndiqueRoute
  '/inteligencia-ia': typeof InteligenciaIaRoute
  '/lgpd': typeof LgpdRoute
  '/para-corretores': typeof ParaCorretoresRoute
  '/para-gestores': typeof ParaGestoresRoute
  '/privacidade': typeof PrivacidadeRoute
  '/produto': typeof ProdutoRoute
  '/sobre': typeof SobreRoute
  '/status': typeof StatusRoute
  '/termos': typeof TermosRoute
  '/vistoria': typeof VistoriaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajuda'
    | '/api-docs'
    | '/blog'
    | '/carreiras'
    | '/clientes'
    | '/contrato'
    | '/docs'
    | '/imprensa'
    | '/indique'
    | '/inteligencia-ia'
    | '/lgpd'
    | '/para-corretores'
    | '/para-gestores'
    | '/privacidade'
    | '/produto'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/vistoria'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajuda'
    | '/api-docs'
    | '/blog'
    | '/carreiras'
    | '/clientes'
    | '/contrato'
    | '/docs'
    | '/imprensa'
    | '/indique'
    | '/inteligencia-ia'
    | '/lgpd'
    | '/para-corretores'
    | '/para-gestores'
    | '/privacidade'
    | '/produto'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/vistoria'
  id:
    | '__root__'
    | '/'
    | '/ajuda'
    | '/api-docs'
    | '/blog'
    | '/carreiras'
    | '/clientes'
    | '/contrato'
    | '/docs'
    | '/imprensa'
    | '/indique'
    | '/inteligencia-ia'
    | '/lgpd'
    | '/para-corretores'
    | '/para-gestores'
    | '/privacidade'
    | '/produto'
    | '/sobre'
    | '/status'
    | '/termos'
    | '/vistoria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjudaRoute: typeof AjudaRoute
  ApiDocsRoute: typeof ApiDocsRoute
  BlogRoute: typeof BlogRoute
  CarreirasRoute: typeof CarreirasRoute
  ClientesRoute: typeof ClientesRoute
  ContratoRoute: typeof ContratoRoute
  DocsRoute: typeof DocsRoute
  ImprensaRoute: typeof ImprensaRoute
  IndiqueRoute: typeof IndiqueRoute
  InteligenciaIaRoute: typeof InteligenciaIaRoute
  LgpdRoute: typeof LgpdRoute
  ParaCorretoresRoute: typeof ParaCorretoresRoute
  ParaGestoresRoute: typeof ParaGestoresRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProdutoRoute: typeof ProdutoRoute
  SobreRoute: typeof SobreRoute
  StatusRoute: typeof StatusRoute
  TermosRoute: typeof TermosRoute
  VistoriaRoute: typeof VistoriaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajuda': {
      id: '/ajuda'
      path: '/ajuda'
      fullPath: '/ajuda'
      preLoaderRoute: typeof AjudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-docs': {
      id: '/api-docs'
      path: '/api-docs'
      fullPath: '/api-docs'
      preLoaderRoute: typeof ApiDocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreiras': {
      id: '/carreiras'
      path: '/carreiras'
      fullPath: '/carreiras'
      preLoaderRoute: typeof CarreirasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contrato': {
      id: '/contrato'
      path: '/contrato'
      fullPath: '/contrato'
      preLoaderRoute: typeof ContratoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprensa': {
      id: '/imprensa'
      path: '/imprensa'
      fullPath: '/imprensa'
      preLoaderRoute: typeof ImprensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indique': {
      id: '/indique'
      path: '/indique'
      fullPath: '/indique'
      preLoaderRoute: typeof IndiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inteligencia-ia': {
      id: '/inteligencia-ia'
      path: '/inteligencia-ia'
      fullPath: '/inteligencia-ia'
      preLoaderRoute: typeof InteligenciaIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lgpd': {
      id: '/lgpd'
      path: '/lgpd'
      fullPath: '/lgpd'
      preLoaderRoute: typeof LgpdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-corretores': {
      id: '/para-corretores'
      path: '/para-corretores'
      fullPath: '/para-corretores'
      preLoaderRoute: typeof ParaCorretoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/para-gestores': {
      id: '/para-gestores'
      path: '/para-gestores'
      fullPath: '/para-gestores'
      preLoaderRoute: typeof ParaGestoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto': {
      id: '/produto'
      path: '/produto'
      fullPath: '/produto'
      preLoaderRoute: typeof ProdutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vistoria': {
      id: '/vistoria'
      path: '/vistoria'
      fullPath: '/vistoria'
      preLoaderRoute: typeof VistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjudaRoute: AjudaRoute,
  ApiDocsRoute: ApiDocsRoute,
  BlogRoute: BlogRoute,
  CarreirasRoute: CarreirasRoute,
  ClientesRoute: ClientesRoute,
  ContratoRoute: ContratoRoute,
  DocsRoute: DocsRoute,
  ImprensaRoute: ImprensaRoute,
  IndiqueRoute: IndiqueRoute,
  InteligenciaIaRoute: InteligenciaIaRoute,
  LgpdRoute: LgpdRoute,
  ParaCorretoresRoute: ParaCorretoresRoute,
  ParaGestoresRoute: ParaGestoresRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProdutoRoute: ProdutoRoute,
  SobreRoute: SobreRoute,
  StatusRoute: StatusRoute,
  TermosRoute: TermosRoute,
  VistoriaRoute: VistoriaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
