ALTER TABLE `website_audit_logs`
  MODIFY `action` ENUM(
    'website_created',
    'website_updated',
    'website_deleted',
    'website_cloned',
    'page_created',
    'page_updated',
    'page_deleted',
    'section_created',
    'section_updated',
    'section_deleted',
    'component_created',
    'component_updated',
    'component_deleted',
    'asset_upload_requested',
    'asset_uploaded',
    'asset_deleted',
    'domain_created',
    'domain_updated',
    'domain_deleted',
    'seo_updated',
    'code_editor_opened',
    'code_file_selected',
    'code_file_created',
    'code_file_updated',
    'code_file_deleted',
    'code_editor_saved'
  ) NOT NULL;

CREATE TABLE `website_code_files` (
  `id` CHAR(36) NOT NULL,
  `company_id` CHAR(36) NOT NULL,
  `website_id` CHAR(36) NOT NULL,
  `page_id` CHAR(36) NULL,
  `file_path` VARCHAR(500) NOT NULL,
  `file_type` VARCHAR(80) NOT NULL,
  `language` VARCHAR(40) NOT NULL,
  `content` LONGTEXT NOT NULL,
  `created_by_id` CHAR(36) NULL,
  `updated_by_id` CHAR(36) NULL,
  `deleted_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `website_code_files_company_id_website_id_file_path_key` (`company_id`, `website_id`, `file_path`),
  KEY `website_code_files_company_id_website_id_file_type_idx` (`company_id`, `website_id`, `file_type`),
  KEY `website_code_files_page_id_idx` (`page_id`),
  KEY `website_code_files_website_id_idx` (`website_id`),
  CONSTRAINT `website_code_files_website_id_fkey` FOREIGN KEY (`website_id`) REFERENCES `websites`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `website_code_files_page_id_fkey` FOREIGN KEY (`page_id`) REFERENCES `website_pages`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
