ALTER TABLE `website_audit_logs`
  MODIFY `action` ENUM(
    'website_created',
    'website_updated',
    'website_deleted',
    'website_cloned',
    'page_created',
    'page_updated',
    'page_deleted',
    'section_created',
    'section_updated',
    'section_deleted',
    'component_created',
    'component_updated',
    'component_deleted',
    'asset_upload_requested',
    'asset_uploaded',
    'asset_deleted',
    'domain_created',
    'domain_updated',
    'domain_deleted',
    'seo_updated',
    'code_editor_opened',
    'code_file_selected',
    'code_file_created',
    'code_file_updated',
    'code_file_deleted',
    'code_editor_saved',
    'site_settings_saved',
    'site_published',
    'site_unpublished',
    'site_property_published',
    'site_property_unpublished'
  ) NOT NULL;
